### PR TITLE
Return error when Cache CR has no template definition. Resolves #1846

### LINKED ISSUE #1846: Slice OOB when Cache .template or .templateName field omitted
If both the `spec.template` and `spec.templateName` fields are omitted and the cluster is of type DataGrid, then the following exception is thrown:

```
2023-08-02T15:13:00.380022006Z 2023-08-02T15:13:00.379Z	INFO	controllers.Cache	----- End Reconciling Cache.	{"Request.Namespace": "pbkn-platformbanking-dev", "Request.Name": "partner"}
....
2023-08-02T15:13:00.380022006Z E0802 15:13:00.379946       1 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:0, signed:true, code:0x1} (runtime error: slice bounds out of range [:1] with length 0)
2023-08-02T15:13:00.380022006Z goroutine 723 [running]:
2023-08-02T15:13:00.380022006Z k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1563660?, 0xc000a2e738})
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x99
2023-08-02T15:13:00.380022006Z k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0006b0b80?})
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
2023-08-02T15:13:00.380022006Z panic({0x1563660, 0xc000a2e738})
2023-08-02T15:13:00.380022006Z 	/usr/lib/golang/src/runtime/panic.go:884 +0x212
2023-08-02T15:13:00.380022006Z github.com/infinispan/infinispan-operator/pkg/mime.GuessMarkup(...)
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/pkg/mime/mime.go:15
2023-08-02T15:13:00.380022006Z github.com/infinispan/infinispan-operator/controllers.(*cacheRequest).reconcileDataGrid(0xc0007d1ba8, 0x50?, {0x18a4c68?, 0xc000bba9c0?})
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/controllers/cache_controller.go:386 +0x935
2023-08-02T15:13:00.380022006Z github.com/infinispan/infinispan-operator/controllers.(*cacheRequest).ispnCreateOrUpdate(0xc0007d1ba8)
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/controllers/cache_controller.go:278 +0x15f
2023-08-02T15:13:00.380022006Z github.com/infinispan/infinispan-operator/controllers.(*CacheReconciler).Reconcile(0xc000118c30, {0x189de28, 0xc000812330}, {{{0xc0004fcc18?, 0x15001c0?}, {0xc0003f4510?, 0xc000b9aa40?}}})
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/controllers/cache_controller.go:216 +0x827
2023-08-02T15:13:00.380022006Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000542d20, {0x189dd80, 0xc00059d5c0}, {0x14d8380?, 0xc0006b0b80?})
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263 +0x303
2023-08-02T15:13:00.380022006Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000542d20, {0x189dd80, 0xc00059d5c0})
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235 +0x1d9
2023-08-02T15:13:00.380022006Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1({0x189dd80, 0xc00059d5c0})
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:198 +0x46
2023-08-02T15:13:00.380022006Z k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x25
2023-08-02T15:13:00.380022006Z k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x1?)
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x3e
2023-08-02T15:13:00.380022006Z k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4866ff?, {0x188a900, 0xc000812240}, 0x1, 0xc0006b7920)
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
2023-08-02T15:13:00.380022006Z k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
2023-08-02T15:13:00.380022006Z k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x189dd80, 0xc00059d5c0}, 0xc000520340, 0xc000466ae0?, 0x0?, 0x0?)
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x99
2023-08-02T15:13:00.380022006Z k8s.io/apimachinery/pkg/util/wait.UntilWithContext({0x189dd80?, 0xc00059d5c0?}, 0xc000d68f68?, 0xc000d68f78?)
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99 +0x2b
2023-08-02T15:13:00.380022006Z created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
2023-08-02T15:13:00.380022006Z 	/remote-source/deps/gomod/src/github.com/infinispan/infinispan-operator/vendor/sigs.k8s.io/controller- runtime/pkg/internal/controller/controller.go:195 +0x466 <-------------------------------
2023-08-02T15:13:00.382159424Z panic: runtime error: slice bounds out of range [:1] with length 0 [recovered]
2023-08-02T15:13:00.382159424Z 	panic: runtime error: slice bounds out of range [:1] with length 0
2023-08-02T15:13:00.382159424Z 
```

~~As one of these fields is required in order for a Cache CR to function, we should add validation to the cache webhook to prevent both fields being empty.~~

We can't add validation to the Cache webhook, as the service type is a property of the Infinispan CR which may not be available at cache creation time. Therefore, we must handle this case in the controller itself.

### PR DESCRIPTION
**Pull request by ryanemerson**

### CODE REVIEW

File: controllers/cache_controller.go [hunk 1]
```diff
@@ -322,8 +322,7 @@ func (r *cacheRequest) reconcileDataGrid(cacheExists bool, cache api.Cache) erro
 	spec := r.cache.Spec
 
 	if spec.Template == "" && spec.TemplateName == "" {
-		r.log.Info("ignoring cache as 'spec.template' and 'spec.TemplateName' are undefined")
-		return nil
+		return fmt.Errorf("unable to reconcile Cachhe as both 'spec.template' and 'spec.TemplateName' are undefined")
```
Comment (Crumby) [inline controllers/cache_controller.go:325]: `Cachhe` -> `Cache`

`spec.template` and `spec.TemplateName` should probably have `template` both either upper case or lower case. (Lower case is what is used in the yaml)
