### PR TITLE
Apply different RemoteStore configuration with ISPN16

### LINKED ISSUE #2369: Infinispan 16 requires different RemoteStore configuration
Hot Rod Rolling upgrades are failing due to changes to RemoteStoro configuration in Infinispan 16. This changes need to be reflected when upgrade type `HotRodRolling` is chosen.

Before ISPN16 configuration:
```
RemoteStore{
	Shared:    true,
	RawValue; true,
	Cache:     cache,
	Segmented: false,
	RemoteServer: &RemoteServer{
		Host: ip,
		Port: constants.InfinispanAdminPort,
	},
	Security: &Security{
		Authentication: &Authentication{
			ServerName: "infinispan",
			Digest: &Digest{
				Username: user,
				Password: pass,
				Realm:    "admin",
			},
		},
	},
}
```
ISPN16+ Configuration
```
RemoteStore{
	Shared:    true,
	Cache:     cache,
	Segmented: false,
	RemoteServer: &RemoteServer{
		Host: ip,
		Port: constants.InfinispanAdminPort,
	},
	Security: &Security{
		Authentication: &Authentication{
			ServerName: "infinispan",
			Digest: &Digest{
				Username: user,
				Password: pass,
				Realm:    "admin",
			},
		},
	},
	Properties: &RemoteStoreProperties{
		Migration: true,
	}
}
```

### PR DESCRIPTION
**Pull request by Crumby**
Closes #2369.

### CODE REVIEW

File: test/e2e/utils/operands.go [hunk 1]
```diff
@@ -5,6 +5,9 @@ import (
 )
 
 func OperandAllowSet() map[string]struct{} {
+	if OperandAllowList == "" {
+		return make(map[string]struct{}, 0)
```
Comment (ryanemerson) [inline test/e2e/utils/operands.go]: Can be simplified to `return make(map[string]struct{})`

File: test/e2e/utils/common.go [hunk 2]
```diff
@@ -494,3 +496,66 @@ func userAndPassword(i *ispnv1.Infinispan, kube *TestKubernetes) (*string, *stri
...
 	return &user, &pass
 }
+
+func CreateCache(cacheName string, encoding mime.MimeType, client HTTPClient) {
+	config := fmt.Sprintf("{\"distributed-cache\":{\"mode\":\"SYNC\",\"remote-timeout\": 60000,\"encoding\":{\"media-type\":\"%s\"}}}", encoding)
+	NewCacheHelper(cacheName, client).Create(config, mime.ApplicationJson)
+}
+
+// addData Populates a cache with bounded parallelism
+func AddDataToPlainCache(cacheName string, entries int, client HTTPClient) {
```
Comment (ryanemerson) [inline test/e2e/utils/common.go]: The comment needs to use the same format as the function name, i.e. `AddDataToPlainCache populates ...`

File: pkg/reconcile/pipeline/infinispan/handler/manage/hotrod_upgrades.go [hunk 3]
```diff
@@ -469,17 +465,19 @@ func (r *HotRodRollingUpgradeRequest) syncData() error {
...
+	podListSource, err := r.PodsCreatedBy(getSourceStatefulSetName(r.i))
 	if err != nil {
-		return err
+		return fmt.Errorf("failed to obtain pods from the source cluster: %w", err)
 	}
+
 	// Clone the source curl client as the credentials are the same, updating the pod to one from the target statefulset
-	targetClient := ctx.InfinispanClientForPod(podList.Items[0].Name)
+	targetClient := ctx.InfinispanClientForPod(podListTarget.Items[0].Name)
+	sourceClient := ctx.InfinispanClientForPod(podListSource.Items[0].Name)
```
Comment (ryanemerson) [inline pkg/reconcile/pipeline/infinispan/handler/manage/hotrod_upgrades.go]: This change still doesn't take into account the operand version of the source cluster, as the code for this method is:

```go
	curlClient := c.curlClient(podName)
	return ispnClient.New(c.Operand(), curlClient)
```

Where `c.Operand` returns the `spec.version`.

I still think we need what I describe [here](https://github.com/infinispan/infinispan-operator/pull/2370#discussion_r2445396599).
