### PR TITLE
Preparation for fix issue #229

### LINKED ISSUE #229: Convert golang e2e test to unit tests
**Issue:** Current GoLand e2e tests used within CI pipeline spin up Minikube and go through process of redeploying Infinispan cluster using Operator per test case which is causing long tests execution per PR.

**Proposal:** Reimplement the tests as unit tests that'd be sending actual and desired state to the Operator/`Reconciler`. The resulting operations from the Operator/`Reconciler` would be then evaluated against expected output.

### PR DESCRIPTION
**Pull request by dmvolod**
As an base operator code frequently changes, it's a preparation for unit testing to fix #229
@rigazilla could you please to look a this small PR.

### CODE REVIEW

File: pkg/controller/infinispan/infinispan_controller.go [hunk 1]
```diff
@@ -75,6 +75,13 @@ func newReconciler(mgr manager.Manager) reconcile.Reconciler {
 	return &ReconcileInfinispan{client: mgr.GetClient(), scheme: mgr.GetScheme()}
 }
 
+// NewFakeReconciler creates a new fake Reconciler for unit testing
```
Comment (rigazilla) [inline pkg/controller/infinispan/infinispan_controller.go]: Is this just for testing? It would be great to keep it separated from implementation code. A separated file would be good, if possible

Comment (dmvolod) [reply pkg/controller/infinispan/infinispan_controller.go]: to move it to the separate file, it would be need to move kubernetes and cluster vars inside ReconcileInfinispan struct and have all fields to be exported

Comment (rigazilla) [reply pkg/controller/infinispan/infinispan_controller.go]: Is this need also if moved in the same package?

Comment (dmvolod) [reply pkg/controller/infinispan/infinispan_controller.go]: Thanks, @rigazilla , just requires RestClient rest.Interface to be changed and exported

**Comment by dmvolod** [comment]
Also, @rigazilla what do you think about moving GetMemoryLimitBytes and GetMaxMemoryUnboundedBytes to the cluster package (from kubernetes) as this is more related to Infinispan cluster pods rather than kubernetes entities?
I would be better for mocking with cluster as not possible to fake it.

**Comment by rigazilla** [comment]
> Also, @rigazilla what do you think about moving GetMemoryLimitBytes and GetMaxMemoryUnboundedBytes to the cluster package (from kubernetes) as this is more related to Infinispan cluster pods rather than kubernetes entities and move GetPassword from cluster to kubernetes and also use ClusterInterface widely?
> I would be better for mocking with cluster as not possible to fake it.

At first sight looks good to me. To avoid to work on code that we'll have to change in the future, please check the your design with the roadmap, mainly: #218, #224, #288. There's nothing defined for them, just try to guess the possible impacts.

**Comment by dmvolod** [comment]
@rigazilla looks like Cache CRD and Operator SDK can potential impact on this, but it could be and merge code quickly, as this is just tests

**Comment by dmvolod** [comment]
@rigazilla . #228 is completed.
Right now, I think this PR will relate to #284 implementation, but without new cache CRD model it's a little bit difficult to guess which methods we will need to implement.

**Comment by rigazilla** [comment]
merged thanks @dmvolod !
