### PR TITLE
[#2243] Avoid to use inline script with template

### LINKED ISSUE #2230: GracefulShutdown upgrade may get stuck in between versions
There's a slight chance for 'TestOperandUpgrades' to fail in between individual version upgrades due to new StatefulSet version not being created.

**Operator log:**
[infinispan-operator-controller-manager-5776c64f76-l889k.log](https://github.com/user-attachments/files/19253863/infinispan-operator-controller-manager-5776c64f76-l889k.log)

**Test log:**
```
2025/03/14 19:22:43 INFO GET: https://test-operand-upgrades-external-datagrid.apps.paris.rhdg-qe.rhocf-dev.net:443/rest/v2/caches/volatileCache?action=size
2025/03/14 19:23:06 INFO GET: https://test-operand-upgrades-external-datagrid.apps.paris.rhdg-qe.rhocf-dev.net:443/rest/v2/container/health/status
2025/03/14 19:23:07 INFO GET: https://test-operand-upgrades-external-datagrid.apps.paris.rhdg-qe.rhocf-dev.net:443/rest/v2/caches/persistentCache?action=size
2025/03/14 19:23:07 INFO Next Operand 15.0.3
2025/03/14 19:23:09 INFO Upgrading Operand to 15.0.3
2025/03/14 19:23:38 INFO Upgrade complete
2025/03/14 19:23:42 INFO GET: https://test-operand-upgrades-external-datagrid.apps.paris.rhdg-qe.rhocf-dev.net:443/rest/v2/container/health/status
2025/03/14 19:23:42 INFO GET: https://test-operand-upgrades-external-datagrid.apps.paris.rhdg-qe.rhocf-dev.net:443/rest/v2/caches/persistentCache?action=size
2025/03/14 19:23:55 INFO GET: https://test-operand-upgrades-external-datagrid.apps.paris.rhdg-qe.rhocf-dev.net:443/rest/v2/caches/volatileCache?action=size
2025/03/14 19:24:14 INFO GET: https://test-operand-upgrades-external-datagrid.apps.paris.rhdg-qe.rhocf-dev.net:443/rest/v2/container/health/status
2025/03/14 19:24:14 INFO GET: https://test-operand-upgrades-external-datagrid.apps.paris.rhdg-qe.rhocf-dev.net:443/rest/v2/caches/persistentCache?action=size
2025/03/14 19:24:14 INFO Next Operand 15.0.4
2025/03/14 19:24:16 INFO Upgrading Operand to 15.0.4
2025/03/14 19:34:17 ERROR timed out waiting for the condition
2025/03/14 19:34:18 ERROR Encountered error: previous terminated container "infinispan" in pod "14-0-13" not found
2025/03/14 19:34:19 ERROR Encountered error: previous terminated container "infinispan" in pod "14-0-17" not found
...
2025/03/14 19:34:22 ERROR Encountered error: unable to write metrics to file for pod '15-0-3:'datagrid': pod not running. status.phase='Succeeded'
2025/03/14 19:34:22 ERROR Encountered error: unable to write metrics to file for pod 'upgrade-backup:'datagrid': pod not running. status.phase='Succeeded'
goroutine 303 [running]:
runtime/debug.Stack()
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x5e
github.com/infinispan/infinispan-operator/test/e2e/utils.TestKubernetes.CleanNamespaceAndLogWithPanic({0xc000d8ecc0}, 0xc0000d2820, {0xc00004c012, 0x8}, {0x15ca3a0, 0xc00058eee0})
	/home/pdrobek/git/infinispan-operator/test/e2e/utils/kubernetes.go:226 +0x1825
github.com/infinispan/infinispan-operator/test/e2e/utils.TestKubernetes.CleanupOLMTest({0x43fce0?}, 0xc0000d2820, {0xc000c22618, 0x13}, {0x186a191, 0x13}, {0xc00004a197, 0x13}, {0xc00004c035, 0xa})
	/home/pdrobek/git/infinispan-operator/test/e2e/utils/olm.go:178 +0x178
panic({0x15ca3a0?, 0xc00058eee0?})
	/usr/lib/golang/src/runtime/panic.go:770 +0x132
github.com/infinispan/infinispan-operator/test/e2e/utils.ExpectNoError(...)
	/home/pdrobek/git/infinispan-operator/test/e2e/utils/asserts.go:21
github.com/infinispan/infinispan-operator/test/e2e/utils.TestKubernetes.WaitForInfinispanStateWithTimeout({0xc000123520?}, {0xc000b9bb78, 0x15}, {0xc000bfbb48, 0x8}, 0x8bb2c97000, 0xc0006c3e30)
	/home/pdrobek/git/infinispan-operator/test/e2e/utils/kubernetes.go:697 +0x116
github.com/infinispan/infinispan-operator/test/e2e/utils.TestKubernetes.WaitForInfinispanState(...)
	/home/pdrobek/git/infinispan-operator/test/e2e/utils/kubernetes.go:682
github.com/infinispan/infinispan-operator/test/e2e/upgrade.TestOperandUpgrades(0xc0000d2820)
	/home/pdrobek/git/infinispan-operator/test/e2e/upgrade/upgrade_operands_test.go:88 +0xcb1
testing.tRunner(0xc0000d2820, 0x194a750)
	/usr/lib/golang/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/usr/lib/golang/src/testing/testing.go:1742 +0x390

    kubernetes.go:227: timed out waiting for the condition 
        
2025/03/14 19:34:29 ERROR Encountered error: previous terminated container "manager" in pod "infinispan-operator-controller-manager-5776c64f76-l889k" not found
2025/03/14 19:34:30 ERROR Encountered error: previous terminated container "olm-operator" in pod "olm-operator-5569b74676-mdggw" not found
2025/03/14 19:34:30 ERROR Encountered error: previous terminated container "catalog-operator" in pod "catalog-operator-bbcfb64d6-lnsdn" not found
--- FAIL: TestOperandUpgrades (1691.07s)
```

### LINKED ISSUE #2243: Remove use of internal server templates from code and documentation
[ISPN-13839](https://issues.redhat.com/browse/ISPN-13839) removed the various `org.infinispan.*` configuration templates from the server in 15.1.0, however we still rely on these templates in parts of the operator test code and our documentation.

We should update the code and all documentation examples to avoid using these templates.

### PR DESCRIPTION
**Pull request by fax4ever**
Closes #2243

(Maybe --- or another similar issue)

### CODE REVIEW

File: test/e2e/upgrade/common.go [hunk 1]
```diff
@@ -242,12 +243,26 @@ func checkServicePorts(t *testing.T, name string) {
...
+func checkBatch(t *testing.T, infinispan *ispnv1.Infinispan) {
+	configMapName := infinispan.Name + "-cm"
+	configMap := &corev1.ConfigMap{
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      configMapName,
+			Namespace: infinispan.Namespace,
+		},
+		Data: map[string]string{
+			batchCtrl.BatchFilename: "create cache --file=/etc/batch/mycache.xml mycache",
+			"mycache.xml":           "<infinispan><cache-container><distributed-cache name=\"mycache\" mode=\"SYNC\" /></cache-container></infinispan>",
```
Comment (ryanemerson) [inline test/e2e/upgrade/common.go:255]: I think we should be able to simplify this to:

`"mycache.xml": "<distributed-cache />"`

Comment (fax4ever) [reply test/e2e/upgrade/common.go:255]: good idea! thanks

**Comment by ryanemerson** [comment]
Thanks @fax4ever, but I think we require additional changes. Feel free to work on the changes required as specified in #2243 if you're interested, or close this PR if time doesn't allow.

**Comment by fax4ever** [comment]
Hi @ryanemerson. About 

> the changes required as specified in https://github.com/infinispan/infinispan-operator/issues/2243

do you mean to:
1. replace the `internal server templates from code` everywhere, also not on the code that is not used by the upgrade tests
2. update the documentation

?
Thanks

**Comment by ryanemerson** [comment]
Yes exactly. We need to make sure there's no usage of `org.infinispan.*` templates anywhere in the repository code and documentation.

**Comment by fax4ever** [comment]
Still missing, to update the doc... tomorrow I'll finish it

File: test/e2e/batch/batch_helper.go [hunk 2]
```diff
@@ -59,3 +62,23 @@ func (b BatchHelper) WaitForValidBatchPhase(name string, phase v2.BatchPhase) *v
...
+	configMap := &corev1.ConfigMap{
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      configMapName,
+			Namespace: infinispan.Namespace,
+		},
+		Data: data,
+	}
+
+	b.testKube.CreateConfigMap(configMap)
+	defer b.testKube.DeleteConfigMap(configMap)
```
[the remark this answers is not in the document]
Comment (fax4ever) [reply test/e2e/batch/batch_helper.go:82]: right! this explain the error also :) thanks Ryan

**Comment by ryanemerson** [comment]
I see there's a few places where we still are using the template:

```
./config/samples/batch/infinispan_v2alpha1_batch.yaml
./config/samples/cache/infinispan_v2alpha1_cache.yaml
./documentation/asciidoc/titles/operator.html
./documentation/asciidoc/topics/proc_creating_caches_hotrod.adoc
./documentation/asciidoc/topics/yaml/batch_inline.yaml
./documentation/asciidoc/topics/yaml/cache_template.yaml
./test-integration/test-server/src/main/java/org/infinispan/operator/remote/auth/hotrod/ClientCertificateAuthenticationServlet.java
./test-integration/test-server/src/main/java/org/infinispan/operator/remote/auth/hotrod/ClientCertificateValidationServlet.java
./test-integration/test-server/src/main/java/org/infinispan/operator/remote/auth/hotrod/HotRodServlet.java
./test/e2e/cache/cache_test.go
```

@Crumby Can you handle the changes required in `test-integration`?

**Comment by fax4ever** [comment]
> I see there's a few places where we still are using the template:
> 
> ```
> ./config/samples/batch/infinispan_v2alpha1_batch.yaml
> ./config/samples/cache/infinispan_v2alpha1_cache.yaml
> ./documentation/asciidoc/titles/operator.html
> ./documentation/asciidoc/topics/proc_creating_caches_hotrod.adoc
> ./documentation/asciidoc/topics/yaml/batch_inline.yaml
> ./documentation/asciidoc/topics/yaml/cache_template.yaml
> ./test-integration/test-server/src/main/java/org/infinispan/operator/remote/auth/hotrod/ClientCertificateAuthenticationServlet.java
> ./test-integration/test-server/src/main/java/org/infinispan/operator/remote/auth/hotrod/ClientCertificateValidationServlet.java
> ./test-integration/test-server/src/main/java/org/infinispan/operator/remote/auth/hotrod/HotRodServlet.java
> ./test/e2e/cache/cache_test.go
> ```
> 
> @Crumby Can you handle the changes required in `test-integration`? I'm happy for it to be in a follow up PR if that's easier.

Yes... I'm trying to update the doc in the meantime

**Comment by fax4ever** [comment]
> I'm trying to update the doc in the meantime

It seems that with the last change I pushed the only `--tempalte` used targets `mytemplate` added as file.
So probably it is still good. Let me know if I can do something more on this contribution. Thanks

**Comment by ryanemerson** [comment]
I see two usages left outside of `test-integration`:

- `./config/samples/cache/infinispan_v2alpha1_cache.yaml`
- `./test/e2e/cache/cache_test.go`

The sample just needs to be updated to use `spec.template` with `<distributed-cache />` instead of `spec.templateName`

**Review by ryanemerson — APPROVED** [review]
Thanks @fax4ever

**Comment by fax4ever** [comment]
Thanks @ryanemerson.

**Comment by ryanemerson** [comment]
Merging with failure as this is caused by the addition of the 15.2.1.Final image and is not related to the changes in this PR.

**Comment by fax4ever** [comment]
Thanks @ryanemerson
