### PR TITLE
[#2194] Fix hr rolling upgrades action name

### LINKED ISSUE #2194: CI is not executing Hot Rod Rolling Upgrade Tests
The `test_hr_rolling_upgrades.yml` is incorrectly calling `make upgrade-test` when it should be calling `make hotrod-upgrade-test`.

### PR DESCRIPTION
**Pull request by fax4ever**
Closes #2194

Draft: need to verify the `test_hr_rolling_upgrades.yml` action execution

### CODE REVIEW

**Comment by fax4ever** [comment]
Looking at the failures I have what it looks like a similar issue for instance if I run two times the `make hotrod-upgrade-test` locally.

On my local machine:
```
kubernetes.go:222: Internal error occurred: failed calling webhook "minfinispan.kb.io": failed to call webhook: Post "https://infinispan-operator-controller-manager-service.namespace-for-testing.svc:443/mutate-infinispan-org-v1-infinispan?timeout=10s": dial tcp 10.96.44.105:443: connect: connection refused 
        
Encountered error: previous terminated container "manager" in pod "infinispan-operator-controller-manager-5d746fd48d-vzczh" not found
Encountered error: previous terminated container "olm-operator" in pod "olm-operator-64cc47587b-wjdg5" not found
Encountered error: previous terminated container "catalog-operator" in pod "catalog-operator-7c4ff7c79b-mf7ft" not found
--- FAIL: TestRollingUpgrade (17.38s)
FAIL
FAIL	github.com/infinispan/infinispan-operator/test/e2e/hotrod-rolling-upgrade	17.410s
FAIL
make: *** [Makefile:125: hotrod-upgrade-test] Error 1
```

On the [CI run](https://github.com/infinispan/infinispan-operator/actions/runs/12670812541/job/35311318454):
```
     kubernetes.go:222: unexpected HTTP status code (500): unexpected error get cache size, response: Error reading header from 1:9939 | 0 
        
Encountered error: previous terminated container "manager" in pod "infinispan-operator-controller-manager-554c96c4f4-s8kct" not found
Encountered error: previous terminated container "olm-operator" in pod "olm-operator-64cc47587b-s9gkm" not found
Encountered error: previous terminated container "catalog-operator" in pod "catalog-operator-7c4ff7c79b-8r29s" not found
--- FAIL: TestUpgrade (1731.63s)
FAIL
FAIL	github.com/infinispan/infinispan-operator/test/e2e/upgrade	3881.792s
FAIL
make: *** [Makefile:120: upgrade-test] Error 1
```

I'm investigating...

File: test/e2e/hotrod-rolling-upgrade/hotrod_rolling_upgrade_test.go [hunk 1]
```diff
@@ -71,7 +71,7 @@ func TestRollingUpgrade(t *testing.T) {
 	entriesPerCache := 100
 	spec := tutils.DefaultSpec(t, testKube, func(i *ispnv1.Infinispan) {
 		i.Spec.Replicas = int32(replicas)
-		i.Spec.Container.CPU = "1000m"
+		i.Spec.Container.CPU = "500m"
```
Comment (ryanemerson) [inline test/e2e/hotrod-rolling-upgrade/hotrod_rolling_upgrade_test.go:74]: I think we should remove this line entirely and depend on the `INFINISPAN_CPU` being set via the action. That way things should be faster when executing locally as we can use more resources.

**Review by ryanemerson — COMMENTED** [review]
It's green :tada:

Just a minor comment.

**Comment by fax4ever** [comment]
Thanks for the review @ryanemerson. I think I applied the change.

**Comment by fax4ever** [comment]
Thanks!
