### PR TITLE
[#2250] Fix TestSpecImage tests using same minor

### LINKED ISSUE #2250: Fix TestSpecImage tests using same minor

### PR DESCRIPTION
**Pull request by fax4ever**
Closes #2250

### CODE REVIEW

File: test/e2e/infinispan/upgrade_operand_test.go [hunk 1]
```diff
@@ -405,3 +404,15 @@ func TestSpecImageUpdate(t *testing.T) {
...
+	versionManager := tutils.VersionManager()
+	latest := versionManager.Latest()
+	latestMinus1 := *versionManager.Operands[len(versionManager.Operands)-2]
+	if (latest.UpstreamVersion.Major == latestMinus1.UpstreamVersion.Major) && (latest.UpstreamVersion.Minor == latestMinus1.UpstreamVersion.Minor) {
+		return latestMinus1, latest
+	}
+
+	latestMinus2 := *versionManager.Operands[len(versionManager.Operands)-3]
+	return latestMinus2, latestMinus1
+}
```
Comment (ryanemerson) [inline test/e2e/infinispan/upgrade_operand_test.go:418]: I think we need a loop here. Currently this works because the operand list is:

```json
                  {
                    "upstream-version": "15.1.5",
                    "image": "quay.io/infinispan/server:15.1.5.Final"
                  },
                  {
                    "upstream-version": "15.1.7",
                    "image": "quay.io/infinispan/server:15.1.7.Final"
                  },
                  {
                    "upstream-version": "15.2.1",
                    "image": "quay.io/infinispan/server:15.2.1.Final"
                  }
```
and we're returning `15.1.5` and `15.1.7`.

However, when we add `15.2.2` we will return `15.1.7` and `15.2.2` which have different minor versions and so the test will fail.

We need a loop/retry mechanism so that we ensure that the two operands are in the same major.minor stream.

File: test/e2e/infinispan/upgrade_operand_test.go [hunk 2]
```diff
@@ -292,13 +292,13 @@ func TestSpecImage(t *testing.T) {
 
 	// Create Infinispan Cluster using the latest Operand version, but using the image of the preceding Operand
 	// Ensures that creating a cluster with an initial spec.image value does not cause infinite StatefulSet updates
-	versionManager := tutils.VersionManager()
-	operand := versionManager.Operands[len(versionManager.Operands)-2]
+	imageOperand, versionOperand := specImageOperands()
```
Comment (ryanemerson) [inline test/e2e/infinispan/upgrade_operand_test.go:295]: The comment needs to be updated to reflect that we're not using the latest operand versions, but rather two operands from the same major.minor stream.

File: test/e2e/infinispan/upgrade_operand_test.go [hunk 3]
```diff
@@ -322,18 +322,17 @@ func TestSpecImageUpdate(t *testing.T) {
 	// release. We can then manually specify spec.image using the FQN of the latest image to simulate a user specifying
 	// custom images
 	replicas := 1
-	versionManager := tutils.VersionManager()
-	operand := versionManager.Operands[len(versionManager.Operands)-2]
+	imageOperand, versionOperand := specImageOperands()
```
Comment (ryanemerson) [inline test/e2e/infinispan/upgrade_operand_test.go:325]: Maybe we can make these variable names more informative, how about "firstOperand, secondOperand"? I don't think "image" and "version" have much meaning in the context of this test.

The comment also needs updating.

File: test/e2e/infinispan/upgrade_operand_test.go (hunk 1 above)
Comment (fax4ever) [reply test/e2e/infinispan/upgrade_operand_test.go:418]: When we add `15.2.2` are you sure we won't return ( `15.2.1` `15.2.2` ) ?

Comment (ryanemerson) [reply test/e2e/infinispan/upgrade_operand_test.go:418]: Yes, my mistake. I miss-read the code.

**Comment by fax4ever** [comment]
Rebased and applied the changed. Thanks for the review @ryanemerson
