### PR TITLE
[#2492] Proper version comparison when using compare api

### LINKED ISSUE #2492: Operator triggers `?compare` rest api only if the micro version is greater then 6
The part of the code that triggers `?action=compare` to compare cache configurations doesn't compare the versions properly. It expects the patch version to be always greater then 6, no matter the major version.

Aside from version check being obviously wrong, it resulted into undetected regression being implemented on the Infinsipan side as the current snapshot version is `16.2.0`, which is suitable for compare endpoint execution but the version but the patch version being 0 makes the controller use older logic

### PR DESCRIPTION
**Pull request by Crumby**
Closes #2492

### CODE REVIEW

File: controllers/cache_controller.go [hunk 1]
```diff
@@ -669,7 +670,11 @@ func configChanged(a, b string, i *v1.Infinispan, caches api.Caches, vm *version
 	// If Operand is >= 14.0.7.Final we can use the cache compare endpoint to avoid unnecessary updates to the
 	// Infinispan spec.template field
 	operand, _ := vm.WithRef(i.Spec.Version)
-	if operand.UpstreamVersion.Major >= 14 && operand.UpstreamVersion.Patch >= 7 {
+
+	minVersion := semver.MustParse("14.0.7")
+	currentVersion, err := semver.Parse(operand.UpstreamVersion.String())
+
+	if err == nil && currentVersion.GE(minVersion) {
```
Comment (ryanemerson) [inline controllers/cache_controller.go]: Can't we just do `if operand.UpstreamVersion.GE(minVersion) {`?

File: controllers/cache_controller.go [hunk 2]
```diff
@@ -669,7 +670,11 @@ func configChanged(a, b string, i *v1.Infinispan, caches api.Caches, vm *version
 	// If Operand is >= 14.0.7.Final we can use the cache compare endpoint to avoid unnecessary updates to the
 	// Infinispan spec.template field
 	operand, _ := vm.WithRef(i.Spec.Version)
-	if operand.UpstreamVersion.Major >= 14 && operand.UpstreamVersion.Patch >= 7 {
+
+	minVersion := semver.MustParse("14.0.7")
```
Comment (ryanemerson) [inline controllers/cache_controller.go]: Should we create a var in `constants.go` so that we're not creating this semver on every reconcilliation?

**Review by ryanemerson — CHANGES_REQUESTED** [review]

File: controllers/cache_controller.go (hunk 1 above)
Comment (Crumby) [reply controllers/cache_controller.go]: Oh, yeah, that's way better

**Comment by ryanemerson** [comment]
`TestUpdateCacheCR` is still failing, do we also need server-side fixes? There's no information in the linked issue, so I'm missing the context here.

The commit message also needs to be updated to reference the correct issue.

**Comment by Crumby** [comment]
@ryanemerson Fixed the commit and updated issue description

**Comment by ryanemerson** [comment]
Thanks @Crumby
