### PR TITLE
Unable to upgrade DataGrid service type with default (empty) Spec.Service.Container.Storage

### LINKED ISSUE #579: Unable to upgrade DataGrid service type with default (empty) Spec.Service.Container.Storage
From version migration: 2.0.x
To version migration: master

Doesn't occurs on migration from 1.1.x

Due to Spec.Service.Container.Storage is defined as "" in 2.0.x by default, additional validations and default setting need to be added.
Error message
```
{"level":"error","ts":1600541738.876798,"logger":"controller_infinispan","msg":"failed to configure new StatefulSet","Request.Namespace":"infinispan-operator","Request.Name":"test-operator-upgrade","error":"quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/dvolodin/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/infinispan/infinispan-operator/pkg/controller/infinispan.(*ReconcileInfinispan).Reconcile\n\t/u01/git/infinispan/infinispan-operator/pkg/controller/infinispan/infinispan_controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/dvolodin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/dvolodin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/dvolodin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/dvolodin/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/dvolodin/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/dvolodin/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
```

#541 need to be merged before

### PR DESCRIPTION
**Pull request by dmvolod**
Fixes #579
#583 need to be merged before for validation

### CODE REVIEW

**Review by ryanemerson — APPROVED** [review]

**Review by rigazilla — APPROVED** [review]

File: pkg/controller/infinispan/infinispan_controller.go [hunk 1]
```diff
@@ -600,6 +600,12 @@ func (r *ReconcileInfinispan) upgradeInfinispan(infinispan *infinispanv1.Infinis
 		infinispan.Spec.Image = nil
 		updateNeeded = true
 	}
+	sc := infinispan.Spec.Service.Container
+	// Remove defined to "" Spec.Service.Container.Storage field for upgrade backward compatibility
+	if sc != nil && sc.Storage != nil && *infinispan.Spec.Service.Container.Storage == "" {
```
Comment (rigazilla) [inline pkg/controller/infinispan/infinispan_controller.go:605]: I'm worried about all the `if` around to deal with backward compatibilities. 
Can a `webhook` approach be of help here?

Comment (dmvolod) [reply pkg/controller/infinispan/infinispan_controller.go:605]: I'm not sure that will be problem, as we are moving from mandatory to optional field type. I'm waiting for upgrade PR's merge for fully validation

Comment (rigazilla) [reply pkg/controller/infinispan/infinispan_controller.go:605]: I was thinking to webhook as a general way for updating cr during upgrade, instead of adding ad hoc code in the cotroller

Comment (dmvolod) [reply pkg/controller/infinispan/infinispan_controller.go:605]: Yeah, @rigazilla agree with you. But it would be nice to wait for update to the Operator SDK 1.x where webhook implementation much more easy than right now. We can use this impl as is and change it in the future.

Comment (rigazilla) [reply pkg/controller/infinispan/infinispan_controller.go:605]: sure @dmvolod, this PR is ok.
I'll look into SDK 1.x, thanks!

**Comment by ryanemerson** [comment]
Thanks @dmvolod
