### PR TITLE
Fix run scripts and add TestOperatorUpgrade function for 2.0.x

### LINKED ISSUE #560: Automates cluster upgrade test
Automates cluster upgrade test not in CI, just for manual testing
The test must accept source and target version parameters, checkout source branch or tag, deploys operator version, create a cluster and than upgrade it to the target version.
#575 need to be resolved before
#576 need to be resolved before
#579 need to be resolved before

### PR DESCRIPTION
**Pull request by dmvolod**
Preparation for fix #560

### CODE REVIEW

File: build/run-okd.sh [hunk 1]
```diff
@@ -4,12 +4,15 @@ OC_USER=${OC_USER:-kubeadmin}
...
-oc login -u ${USER}
-oc project default
+oc login -u "${OC_USER}"
+oc project "${PROJECT_NAME}"
 oc apply -f deploy/role.yaml
+oc apply -f deploy/clusterrole.yaml
 oc apply -f deploy/service_account.yaml
 oc apply -f deploy/role_binding.yaml
-oc apply -f deploy/operator.yaml
+sed -e "s|namespace:.*|namespace: ${PROJECT_NAME}|" deploy/clusterrole_binding.yaml | oc apply -f -
```
Comment (ryanemerson) [inline build/run-okd.sh:15]: This line isn't present on the `master` branch. Do we need it there as well?

**Review by ryanemerson — APPROVED** [review]

File: build/run-okd.sh (hunk 1 above)
Comment (dmvolod) [reply build/run-okd.sh:15]: Yes, this will be part of the #560 and this PR just preparation for it

**Comment by ryanemerson** [comment]
Thanks @dmvolod
